In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
transaction =[
    ['Milk', 'Butter','Oats'],
    ['Milk', 'Bread', 'Butter'],
    ['Cheese', 'Jam' , 'Bread', 'Egg'],
    ['Bread','Egg', 'Cheese'],
    ['Milk', 'Oats', 'Bread'],
    ['Butter', 'Oats'],
    ['Butter' , 'Bread', 'Cheese'],
    ['Bread', 'Cheese', 'Egg']
]

In [3]:
te = TransactionEncoder()
te_array = te.fit_transform(transaction)
df = pd.DataFrame(te_array,columns=te.columns_)

In [4]:
df

   Bread  Butter  Cheese    Egg    Jam   Milk   Oats
0  False    True   False  False  False   True   True
1   True    True   False  False  False   True  False
2   True   False    True   True   True  False  False
3   True   False    True   True  False  False  False
4   True   False   False  False  False   True   True
5  False    True   False  False  False  False   True
6   True    True    True  False  False  False  False
7   True   False    True   True  False  False  False

In [20]:
frequent_itemsets = apriori(df, min_support=0.2,use_colnames=True)
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=0.67)

In [22]:
print(frequent_itemsets)

    support              itemsets
0     0.750               (Bread)
1     0.500              (Butter)
2     0.500              (Cheese)
3     0.375                 (Egg)
4     0.375                (Milk)
5     0.375                (Oats)
6     0.250       (Butter, Bread)
7     0.500       (Bread, Cheese)
8     0.375          (Bread, Egg)
9     0.250         (Milk, Bread)
10    0.250        (Butter, Milk)
11    0.250        (Oats, Butter)
12    0.375         (Cheese, Egg)
13    0.250          (Oats, Milk)
14    0.375  (Bread, Egg, Cheese)

In [14]:
print(rules)
# we work mainly on antecedent_support, jaccard, lift

        antecedents      consequents  antecedent support  consequent support  \
0           (Bread)         (Cheese)               0.750               0.500
1          (Cheese)          (Bread)               0.500               0.750
2           (Bread)            (Egg)               0.750               0.375
3             (Egg)          (Bread)               0.375               0.750
4            (Milk)          (Bread)               0.375               0.750
5           (Bread)           (Milk)               0.750               0.375
6          (Butter)           (Milk)               0.500               0.375
7            (Milk)         (Butter)               0.375               0.500
8            (Oats)         (Butter)               0.375               0.500
9          (Butter)           (Oats)               0.500               0.375
10         (Cheese)            (Egg)               0.500               0.375
11            (Egg)         (Cheese)               0.375               0.500
12           (Oats)           (Milk)               0.375               0.375
13           (Milk)           (Oats)               0.375               0.375
14     (Bread, Egg)         (Cheese)               0.375               0.500
15  (Bread, Cheese)            (Egg)               0.500               0.375
16    (Cheese, Egg)          (Bread)               0.375               0.750
17          (Bread)    (Cheese, Egg)               0.750               0.375
18            (Egg)  (Bread, Cheese)               0.375               0.500
19         (Cheese)     (Bread, Egg)               0.500               0.375

    support  confidence      lift  representativity  leverage  conviction  \
0     0.500    0.666667  1.333333               1.0  0.125000      1.5000
1     0.500    1.000000  1.333333               1.0  0.125000         inf
2     0.375    0.500000  1.333333               1.0  0.093750      1.2500
3     0.375    1.000000  1.333333               1.0  0.093750         inf
4     0.250    0.666667  0.888889               1.0 -0.031250      0.7500
5     0.250    0.333333  0.888889               1.0 -0.031250      0.9375
6     0.250    0.500000  1.333333               1.0  0.062500      1.2500
7     0.250    0.666667  1.333333               1.0  0.062500      1.5000
8     0.250    0.666667  1.333333               1.0  0.062500      1.5000
9     0.250    0.500000  1.333333               1.0  0.062500      1.2500
10    0.375    0.750000  2.000000               1.0  0.187500      2.5000
11    0.375    1.000000  2.000000               1.0  0.187500         inf
12    0.250    0.666667  1.777778               1.0  0.109375      1.8750
13    0.250    0.666667  1.777778               1.0  0.109375      1.8750
14    0.375    1.000000  2.000000               1.0  0.187500         inf
15    0.375    0.750000  2.000000               1.0  0.187500      2.5000
16    0.375    1.000000  1.333333               1.0  0.093750         inf
17    0.375    0.500000  1.333333               1.0  0.093750      1.2500
18    0.375    1.000000  2.000000               1.0  0.187500         inf
19    0.375    0.750000  2.000000               1.0  0.187500      2.5000

    zhangs_metric   jaccard  certainty  kulczynski
0        1.000000  0.666667   0.333333    0.833333
1        0.500000  0.666667   1.000000    0.833333
2        1.000000  0.500000   0.200000    0.750000
3        0.400000  0.500000   1.000000    0.750000
4       -0.166667  0.285714  -0.333333    0.500000
5       -0.333333  0.285714  -0.066667    0.500000
6        0.500000  0.400000   0.200000    0.583333
7        0.400000  0.400000   0.333333    0.583333
8        0.400000  0.400000   0.333333    0.583333
9        0.500000  0.400000   0.200000    0.583333
10       1.000000  0.750000   0.600000    0.875000
11       0.800000  0.750000   1.000000    0.875000
12       0.700000  0.500000   0.466667    0.666667
13       0.700000  0.500000   0.466667    0.666667
14       0.800000  0.750000   1.000000    0.875000
15       1.000000  0.750000   0.600000    0.875000
16       0.400000  0.500000   1.000000    0.750000
17       1.000000  0.500000   0.200000    0.750000
18       0.800000  0.750000   1.000000    0.875000
19       1.000000  0.750000   0.600000    0.875000